services:
  - type: web
    name: techstorm-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: TechStorm API
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.kloqndxqnernodizotxc.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: BROADCAST_CONNECTION
        value: pusher
      - key: PUSHER_APP_ID
        value: 2099575
      - key: PUSHER_APP_KEY
        value: 15baedd963ed4f63a74d
      - key: PUSHER_APP_SECRET
        sync: false
      - key: PUSHER_APP_CLUSTER
        value: eu
      - key: SUPABASE_URL
        value: https://kloqndxqnernodizotxc.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: products
      - key: FILESYSTEM_DISK
        value: supabase
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
